version: '3'

services:
  web:
    build: .
    command: sh -c "/wait-for-it.sh redis:6379 -- uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery-worker
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER}
      - CELERY_RESULT_BACKEND=${CELERY_BROKER}

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    command: celery -A app.celery_config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER}
      - CELERY_RESULT_BACKEND=${CELERY_BROKER}
